version: '3.8'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongodb:27017/marketpulse
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
volumes:
  mongodb_data: